/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Adapter.GUIFrameworkAdapter;
import PublicClasses.PluginObject;
import java.awt.BorderLayout;
import java.awt.Container;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author rootkid
 */
public class FrameworkGUI extends javax.swing.JFrame {

    /**
     * Creates new form FrameworkGUI
     *
     *
     */
    private GUIFrameworkAdapter _adapter;
    private List<GUIGeneric> tabList = new ArrayList<GUIGeneric>();

    public FrameworkGUI() throws IOException {
        initComponents();
        _adapter = new GUIFrameworkAdapter();
        _adapter.setGUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPanel = new javax.swing.JTabbedPane();
        Menu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        RefreshGUI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileMenu.setText("File");

        RefreshGUI.setText("Refresh GUI");
        RefreshGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshGUIActionPerformed(evt);
            }
        });
        FileMenu.add(RefreshGUI);

        Menu.add(FileMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshGUIActionPerformed
        // TODO add your handling code here:
        //load all registered instances
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                for (PluginObject po : _adapter.getRegisteredPlugins()) {
                    //create tabs
                    GUIGeneric tab = new GUIGeneric(po.getPluginName(), _adapter);
                    tabList.add(tab);
                    TabPanel.addTab(po.getPluginName(), tab);
                    System.out.println(po);
                    System.out.println("Generic Tab should be (lol) added");
                }
            }

        });
    }//GEN-LAST:event_RefreshGUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameworkGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrameworkGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    public void showMessage(final String message, final String plugin) {
        //todo
        //update Textfield for plugin with message
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                for (GUIGeneric tab : tabList) {
                    if (tab.getInstance().equals(plugin)) {
                        tab.showMessage(message);
                        System.out.println("ShowMessage in FrameworGUI called");
                    }
                }
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem RefreshGUI;
    private javax.swing.JTabbedPane TabPanel;
    // End of variables declaration//GEN-END:variables
}
